# Advent of Code 2021 day 13

### data input

In [1]:
import numpy as np

# devided the input into "points" and "fold instructions"
#raw_file = 'day13.txt'
raw_file = 'day13_test.txt'

with open(raw_file) as file:
    input = file.readlines()

data = [row.strip() for row in input]
data = [x.split(',') for x in data]
data = [[int(x) for x in r] for r in data]

col_length = len(data)
row_length = len(data[0])

print(len(data))
#data

18


---

#### create the transparent paper

In [2]:
# find the highest value of the coordinates
max_x = 0
max_y = 0

for x in data:
    if x[0] > max_x:
        max_x = x[0]
    if x[1] > max_y:
        max_y = x[1]

x_length = max_x+1 #max(data[0]) + 1
y_length = max_y+1 #max(data[1]) + 1
print(x_length)
print(y_length)

11
15


In [8]:
# initialize the paper with zeros
paper = np.zeros((y_length,x_length), int)
paper

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
# fill the paper with the dots
for x in data:
    paper[x[1]][x[0]] = 99
paper

array([[ 0,  0,  0, 99,  0,  0, 99,  0,  0, 99,  0],
       [ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [99,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 99,  0,  0,  0,  0, 99,  0, 99],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 99,  0,  0,  0,  0, 99,  0, 99, 99,  0],
       [ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 99,  0,  0,  0, 99],
       [99,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [99,  0, 99,  0,  0,  0,  0,  0,  0,  0,  0]])

---

#### methods to fold

In [5]:
def vertical_fold(fold_col, paper):
    for row_index, x in enumerate(paper):
        for col_index, y in enumerate(x):
            if col_index > fold_col:
                if paper[row_index][col_index] > 0:
                    paper[row_index][fold_col-(col_index-fold_col)] = 33
    # return only the folded section of the paper
    return paper[:,:fold_col]

In [6]:
def horizontal_fold(fold_row, paper):
    for row_index, x in enumerate(paper):
        for col_index, y in enumerate(x):
            if row_index > fold_row:
                if paper[row_index][col_index] > 0:
                    paper[fold_row-(row_index-fold_row)][col_index] = 33
    # return only the folded section of the paper
    return paper[:fold_row]

---

### Part 1

In [7]:
if 'test' in raw_file:
    fold = ['y',7]
else:
    fold = ['x',655]

if fold[0] == 'y':
    paper = horizontal_fold(fold[1], paper)
elif fold[0] == 'x':
    paper = vertical_fold(fold[1], paper)
    
print(paper)
print(np.count_nonzero(paper))

[[33  0 33 99  0  0 99  0  0 99  0]
 [33  0  0  0 99  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 33  0  0  0 33]
 [99  0  0  0 33  0  0  0  0  0  0]
 [ 0 33  0 99  0  0 33  0 33 33 99]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
17


---

### Part 2

ATTENTION: reset the paper before executing part 2, i.e. initialize with zeros and add the dots

In [ ]:
# I was too tired and just hard coded the folds
folds = [
['x',655],
['y',447],
['x',327],
['y',223],
['x',163],
['y',111],
['x',81],
['y',55],
['x',40],
['y',27],
['y',13],
['y',6]]

In [ ]:
for fold in folds:
    if fold[0] == 'y':
        paper = horizontal_fold(fold[1], paper)
        #print(f'do horizontal fold: {fold}')
    elif fold[0] == 'x':
        paper = vertical_fold(fold[1], paper)
        #print(f'do vertical fold: {fold}')
print(paper)
print(paper.shape)

---
for the test data:

In [10]:
test_folds = [['y',7], ['x',5]]

for fold in test_folds:
    if fold[0] == 'y':
        paper = horizontal_fold(fold[1], paper)
        print(f'do horizontal fold: {fold}')
    elif fold[0] == 'x':
        paper = vertical_fold(fold[1], paper)
        print(f'do vertical fold: {fold}')
print(paper)
print(paper.shape)

do horizontal fold: ['y', 7]
do vertical fold: ['x', 5]
[[33 33 33 99 33]
 [33  0  0  0 99]
 [33  0  0  0 33]
 [99  0  0  0 33]
 [33 33 33 99 33]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
(7, 5)
